### ISSUE TITLE
No Assistant is loaded

### ISSUE THREAD

**Issue by uday31in** [Azure-Samples/azureai-assistant-tool#10]
<img width="1302" alt="image" src="https://github.com/Azure-Samples/azureai-assistant-tool/assets/14359777/62ed2bad-205e-4820-bf59-34094fe2867c">

**Comment by jhakulin** [comment]
@uday31in thanks for the report, did you create assistant under assistant menu?

**Comment by uday31in** [comment]
UI cannot render the available models to create new assistant.

<img width="636" alt="image" src="https://github.com/Azure-Samples/azureai-assistant-tool/assets/14359777/eb161777-15aa-4b3b-85b9-59fb3ead4174">

**Comment by uday31in** [comment]
Never mind, it a text input and i can type the input.

**Comment by jhakulin** [comment]
@uday31in that is true, using Azure listing the model deployment names is little cumbersome and for now the tool requires to set the deployment name. We are looking at creating more convenient ways to get deployments listed programmatically.
