### ISSUE TITLE
where azure deployment can be set?

### ISSUE THREAD

**Issue by wweyl** [Azure-Samples/azureai-assistant-tool#13]
An error occurred when I ran the sample code, and the logs is as follows:
$ cd samples/PetTravelPlanChatAssistant
$ python main.py
```
user: hi
An error occurred: Error occurred during processing run: Error code: 404 - {'error': {'code': 'DeploymentNotFound', 'message': 'The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.'}}
```
It seems that the 'azure_deployment' parameter have not been set in AzureOpenAI, but I couldn't find where to set it.
Does anyone kindly know how to solve this issue? 

### OS and Version?
> macOS 14.4.1 

### Versions
> git main

**Comment by jhakulin** [comment]
@wweyl Thanks for report, in that sample you need to set the model information in YAML file, https://github.com/Azure-Samples/azureai-assistant-tool/blob/main/samples/PetTravelPlanChatAssistant/config/PetTravelPlanChatAssistant_assistant_config.yaml

model: <Your Azure Model Deployment Name>

There is by default gpt-4-1106-preview as value now.

**Comment by wweyl** [comment]
@jhakulin  it's ok now. thanks for support.
