### ISSUE TITLE
Assistants.create() got an unexpected keyword argument 'file_ids'

### ISSUE THREAD

**Issue by amy-why-msft** [Azure-Samples/azureai-assistant-tool#15]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> clone the repo, create a new virtual python environment, follow the steps to install the tool

### Any log messages given by the failure
>2024-04-22 12:46:21,767 - ERROR - _create_assistant - Failed to create new assistant with name: amytest: Assistants.create() got an unexpected keyword argument 'file_ids'
2024-04-22 12:46:21,767 - ERROR - _init_assistant_client - Failed to initialize assistant instance: Failed to create new assistant with name: amytest: Assistants.create() got an unexpected keyword argument 'file_ids'

### Expected/desired behavior
> be able to create a new assistant.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

Windows 11
### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by amy-why-msft** [comment]
This is due to latest OpenAI updates and tool probably installs the latest openai library and that causes issue
pip install openai==1.20.0
resolves the issue

**Comment by jhakulin** [comment]
New version 0.3.0-alpha has been released for V2 api support.
https://github.com/Azure-Samples/azureai-assistant-tool/releases/tag/v0.3.0-alpha
