### ISSUE TITLE
Assistants V2

### ISSUE THREAD

**Issue by msi-martinsen** [Azure-Samples/azureai-assistant-tool#19]
Hi it is seems like the latest version are using a higher version of openAI, but one that is not supported by Azure OpenAI.
Could you please make it possible to use 1.20 openAI until support for Assistants V2 is implemented.
Chat works fine, but assistants are failing.

**Comment by jhakulin** [comment]
Hi,

AZURE_OPENAI_API_VERSION=2024-05-01-preview will support tool resources. This API version is not yet officially latest version, but it is available in
https://github.com/Azure/azure-rest-api-specs/tree/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/preview/2024-05-01-preview

You can set this version to use Azure Assistants with the latest OpenAI library versions with the tool.

Alternatively

Take latest v0.2.12-alpha branch content from https://github.com/Azure-Samples/azureai-assistant-tool repository for UI
Install azure-ai-assistant library 0.2.12a version.
Install openai 1.20.0 version or earlier.

**Comment by jhakulin** [comment]
Closing as V2 support for assistants is available for Azure OpenAI now with 2024-05-01-preview version.
