### ISSUE TITLE
Add the requirement to install setuptools

### ISSUE THREAD

**Issue by uday31in** [Azure-Samples/azureai-assistant-tool#9]
https://github.com/Azure-Samples/azureai-assistant-tool?tab=readme-ov-file#step-4-install-python-ui-libraries

This requires setuptools.

```
pip install setuptools      
```

> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
```
(.venv) user@192 azure-ai-assistant % python setup.py sdist bdist_wheel
Traceback (most recent call last):
  File "/Users/<user>/git/upstream/azureai-assistant-tool/sdk/azure-ai-assistant/setup.py", line 4, in <module>
    from setuptools import setup, find_packages
ModuleNotFoundError: No module named 'setuptools'
```

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jhakulin** [comment]
@uday31in We will add to README.md, thanks!

**Comment by jhakulin** [comment]
Will be fixed this week's release
